Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Included Library
cuda
NVIDIA GeForce GTX 1080 Ti
Memory Usage:
Allocated: 0.0 GB
Cached:    0.0 GB
   Unnamed: 0  ...                                         issue_body
0           0  ...  I just discovered Gitlens and find the functio...
1           1  ...                                                NaN
2           2  ...                                                NaN
3           3  ...  Currently the loading wheel is a fixed size in...
4           4  ...                    To bring magneto stick floating

[5 rows x 8 columns]
bug            361103
enhancement    299374
question        62422
Name: issue_label, dtype: int64
{'bug': 0, 'enhancement': 1, 'question': 2}
   issue_label                                         issue_data  label
0          bug  Welcome screen on every editor window is very ...      0
1          bug  "pcopy invite" and "pcopy paste abc:" does not...      0
2          bug  UI: Modal overlay is half transparent, shouldn...      0
3  enhancement  Make the loading screen scale with browser win...      1
4          bug  Spectator - Investigate a way to strip weapons...      0
   issue_label                                         issue_data  label
0          bug  Welcome screen on every editor window is very ...      0
1          bug  "pcopy invite" and "pcopy paste abc:" does not...      0
2          bug  UI: Modal overlay is half transparent, shouldn...      0
3  enhancement  Make the loading screen scale with browser win...      1
4          bug  Spectator - Investigate a way to strip weapons...      0
   issue_label                                         issue_data  label
0  enhancement  ERROR: KeyError: key (TIFF.SAMPLEFORMAT_INT, 0...      1
1  enhancement                 Add database backup to dropbox nan      1
2  enhancement  Add a button/method to open the Source or Outp...      1
3          bug  Processes are being started twice At some poin...      0
4          bug                          Cannot add hp to wall nan      0
   issue_label                                         issue_data  label
0  enhancement  ERROR: KeyError: key (TIFF.SAMPLEFORMAT_INT, 0...      1
1  enhancement                 Add database backup to dropbox nan      1
2  enhancement  Add a button/method to open the Source or Outp...      1
3          bug  Processes are being started twice At some poin...      0
4          bug                          Cannot add hp to wall nan      0
Done train encoding
Done val encoding
Done test encoding
614464 108435 80518
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/site-packages/transformers/file_utils.py", line 2704, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/site-packages/transformers/optimization.py", line 26, in <module>
    from .trainer_utils import SchedulerType
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/site-packages/transformers/trainer_utils.py", line 47, in <module>
    import tensorflow as tf
  File "/afs/crc.nd.edu/user/m/msiddiq3/.local/lib/python3.9/site-packages/tensorflow/__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/afs/crc.nd.edu/user/m/msiddiq3/.local/lib/python3.9/site-packages/tensorflow/python/__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "/afs/crc.nd.edu/user/m/msiddiq3/.local/lib/python3.9/site-packages/tensorflow/python/eager/context.py", line 25, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/m/msiddiq3/Public/NLBSE-Tool-Competition/code_torch.py", line 204, in <module>
    from transformers import AdamW, get_linear_schedule_with_warmup
  File "<frozen importlib._bootstrap>", line 1055, in _handle_fromlist
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/site-packages/transformers/file_utils.py", line 2694, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/afs/crc.nd.edu/user/m/msiddiq3/.conda/envs/nlbse/lib/python3.9/site-packages/transformers/file_utils.py", line 2706, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.optimization because of the following error (look up to see its traceback):
No module named 'absl'
